name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: lint
        run: |
          zig fmt --check src/ build.zig build.zig.zon

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: build
        run: zig build test